version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scanner_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  springboot-app:
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/scanner_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "9091:9090"
    depends_on:
      - mysql

volumes:
  mysqldata:
